### PR TITLE
Fix git submodules

### LINKED ISSUE #17: Git Submodules Not Working
## what
* Submodules are not working

## why
* We do a recursive clone, but only on the master branch
* We should do a recursive update after checkout instead

## references
* https://github.com/cloudposse/atlantis/blob/3b2ed122e0477bd62af456b0de774df56e1805ed/server/events/working_dir.go#L165-L170
* https://stackoverflow.com/a/29156667/1237191

### PR DESCRIPTION
**Pull request by aknysh**
## what
* Fix git submodules

## why
* We should do a recursive update after checkout 
* closes #17

### CODE REVIEW

File: server/events/working_dir.go [hunk 1]
```diff
@@ -147,27 +147,43 @@ func (w *FileWorkspace) forceClone(log *logging.SimpleLogger,
...
 	}
 
-	// Check out the branch for this PR.
-	log.Info("checking out branch %q", p.Branch)
-	checkoutCmd := exec.Command("git", "checkout", p.Branch) // #nosec
-	checkoutCmd.Dir = cloneDir
-	if err := checkoutCmd.Run(); err != nil {
-		return "", errors.Wrapf(err, "checking out branch %s", p.Branch)
+	// Recursively update submodules for the branch
+	log.Info("updating submodules for branch %q", p.Branch)
```
Comment (osterman) [inline server/events/working_dir.go:171]: Will this work if:
a) no submodules defined
b) without calling `git submoule init` first?

Comment (aknysh) [reply server/events/working_dir.go:171]: a) tested on a repo w/o submodules, the command just returns w/o any errors
b) merged into one command `git submodule update --init --recursive`, tested on repos with and without submodules

**Review by osterman — APPROVED** [review]
